Cms\ProductManagerBundle\Entity\ProductOptionGroupTypes:
    type: entity
    table: product_option_group_types
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        optionType:
            type: string
            length: '100'
    oneToMany:
        optionGroups:
            targetEntity: ProductOptionGroups
            mappedBy: optionGroupType
    lifecycleCallbacks: {  }
