Cms\ProductManagerBundle\Entity\ProductCategories:
    type: entity
    table: product_categories
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductCategoriesRepository
    gedmo:
        tree:
          type: nested
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
            nullable: TRUE
            gedmo:
              timestampable:
                on: create
        modified:
            type: time
            nullable: TRUE
            gedmo:
              timestampable:
                on: update
        modifiedBy:
            type: integer
            nullable: TRUE
        lft:
          type: integer
          gedmo:
            - treeLeft
        rgt:
          type: integer
          gedmo:
            - treeRight
        root:
          type: integer
          nullable: true
          gedmo:
            - treeRoot
        lvl:
          type: integer
          gedmo:
            - treeLevel
    oneToMany:
        children:
            targetEntity: Cms\ProductManagerBundle\Entity\ProductCategories
            mappedBy: parent
            orderBy:
                lft: ASC
        definitions:
            targetEntity: Cms\Entity\ProductCategoryDefinitions
            mappedBy: productCategory
            cascade: [persist]
    manyToOne:
        parent:
            targetEntity: Cms\ProductManagerBundle\Entity\ProductCategories
            inversedBy: children
            joinColumn:
                name: parentId
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
            - treeParent
    manyToMany:
        products:
            targetEntity: Cms\Entity\Products
            mappedBy: categories
    lifecycleCallbacks: {  }
