Cms\ProductManagerBundle\Entity\ProductTypes:
    type: entity
    table: product_types
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductTypesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productType:
            type: string
            length: '40'
        typeDescription:
            type: text
    oneToMany:
        products:
            targetEntity: Cms\Entity\Products
            mappedBy: productType
    lifecycleCallbacks: {  }
