Cms\ProductManagerBundle\Entity\ProductAttributeDefinitions:
    type: entity
    table: null
    repositoryClass: Cms\ProductManagerBundle\Entity\ProductAttributeDefinitionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
