Cms\ProductManagerBundle\Entity\ProductCategoryTranslations:
    type: entity
    table: product_category_translations
    repositoryClass: Cms\ProductManagerBundle\Repository\ProductCategoryTranslationsRepository
    indexes:
        product_category_index:
          columns: [ locale, object_class, field, foreign_key ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 8
            gedmo:
        objectClass:
            column: object_class
            type: string
            length: 255
        field:
            type: string
            length: 32
        foreignKey:
            column: foreign_key
            type: string
            length: 64
        content:
            type: text
    lifecycleCallbacks: {  }
