Cms\ProductManagerBundle\Entity\ProductPrices:
    type: entity
    table: product_prices
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductPricesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productVarientId:
            type: integer
            nullable: TRUE
        productId:
            type: integer
            nullable: TRUE
        nowPrice:
            type: decimal
        wasPrice:
            type: decimal
        wholesalePrice:
            type: decimal
        currencyId:
            type: integer
        zoneId:
            type: integer
    oneToOne:
        zone:
            targetEntity: Cms\Entity\Zones
            joinColumn:
                name: zoneId
                referencedColumnName: id
        currency:
            targetEntity: Currencies
            joinColumn:
                name: currencyId
                referencedColumnName: id

    lifecycleCallbacks: {  }
