Cms\ProductManagerBundle\Entity\ProductOptions:
    type: entity
    table: product_options
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductOptionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productOptionGroupsId:
            type: integer
        optionValue:
            type: string
            length: '100'
        optionPriority:
            type: integer
    oneToMany:
        definitions:
            targetEntity: Cms\Entity\ProductOptionDefinitions
            mappedBy: productOption
    lifecycleCallbacks: {  }
