Cms\ProductManagerBundle\Entity\ProductAttributes:
    type: entity
    table: PRODUCT_Attributes
    repositoryClass: Cms\ProductManagerBundle\Entity\ProductAttributesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productId:
            type: integer

    lifecycleCallbacks: {  }
