Cms\ProductManagerBundle\Entity\ProductCategories:
    type: entity
    table: product_categories
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductCategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        parentProductCategoryId:
            type: integer
            nullable: TRUE
        created:
            type: datetime
            nullable: TRUE
            gedmo:
              timestampable:
                on: create
        modified:
            type: time
            nullable: TRUE
            gedmo:
              timestampable:
                on: update
        modifiedBy:
            type: integer
            nullable: TRUE
    properties:
        parentProductCategoryId:
            - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
    oneToMany:
        children:
            targetEntity: Cms\Entity\ProductCategories
            mappedBy: parent
            cascade: [persist]
        definitions:
            targetEntity: Cms\Entity\ProductCategoryDefinitions
            mappedBy: productCategory
            cascade: [persist]
    manyToOne:
        parent:
            targetEntity: Cms\Entity\ProductCategories
            inversedBy: children
            joinColumn:
                name: parentProductCategoryId
                referencedColumnName: id
    manyToMany:
        products:
            targetEntity: Cms\Entity\Products
            mappedBy: categories
    lifecycleCallbacks: {  }
