Cms\ProductManagerBundle\Entity\ProductCategory:
    type: entity
    table: product_categories
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductCategoryRepository
    gedmo:
        tree:
            type: nested
#        translation:
#            lxocale: locale
#            entity: Cms\ProductManagerBundle\Entity\ProductCategoryTranslations
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productCategoryName:
            type: string
            length: 255
            gedmo:
              - translatable
        created:
            type: datetime
            nullable: TRUE
            gedmo:
              timestampable:
                on: create
        modified:
            type: datetime
            nullable: TRUE
            gedmo:
              timestampable:
                on: update
        modifiedBy:
            type: integer
            nullable: TRUE
        lft:
          type: integer
          gedmo:
            - treeLeft
        rgt:
          type: integer
          gedmo:
            - treeRight
        root:
          type: integer
          nullable: true
          gedmo:
            - treeRoot
        lvl:
          type: integer
          gedmo:
            - treeLevel
    oneToMany:
        children:
            targetEntity: Cms\ProductManagerBundle\Entity\ProductCategory
            mappedBy: parent
            orderBy:
                lft: ASC
    manyToOne:
        parent:
            targetEntity: Cms\ProductManagerBundle\Entity\ProductCategory
            inversedBy: children
            joinColumn:
                name: parentId
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
#    manyToMany:
#        products:
#            targetEntity: Cms\Entity\Products
#            mappedBy: categories
    lifecycleCallbacks: {  }
