Cms\ProductManagerBundle\Entity\ProductOptionGroupDefinitions:
    type: entity
    table: product_option_group_definitions
    repositoryClass: Cms\ProductManagerBundle\Entity\Repository\ProductOptionGroupDefinitionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productOptionGroupName:
            type: string
            length: '150'
        languageId:
            type: integer
        productOptionGroupId:
            type: integer
    manyToOne:
        productOptionGroup:
            targetEntity: Cms\Entity\ProductOptionGroups
            inversedBy: definitions
            joinColumn:
                name: productOptionGroupId
                referencedColumnName: id
    lifecycleCallbacks: {  }
