services:
    oni_product_category_form:
        class: Oni\ProductManagerBundle\Form\ProductCategoryForm
        factory: [ '@oni_product_category_form_factory', getService ]
        arguments:
                - "@service_container"
        tags:
              - { name: form.type, alias: oni_product_category_form }
    oni_product_type:
        class: Oni\ProductManagerBundle\Form\ProductType
        factory: [ '@oni_product_form_factory', getService ]
        arguments:
                - "@service_container"
        tags:
                - { name: form.type, alias: oni_product_form }
    oni_product_option_form:
        class: Oni\ProductManagerBundle\Form\ProductOptionGroupForm
        arguments:
                - "@oni_product_option_service"
        tags:
              - { name: form.type, alias: oni_product_option_form }
    oni_product_prices_type:
        class: Oni\ProductManagerBundle\Form\ProductPriceType
        tags:
              - { name: form.type, alias: oni_product_price_form }