add_product:
    path:     /admin/products/add
    defaults: { _controller: product_controller:Index:add }

product_list:
    path:     /admin/products
    defaults: { _controller: product_controller:indexAction  }

edit_product:
    path:     /admin/products/edit
    defaults: { _controller: product_controller:Index:edit }

add_category:
    path:     /admin/product/category/add
    defaults: { _controller: product_categories_controller:addAction }

categories_list:
    path:     /admin/product/categories
    defaults: { _controller: product_categories_controller:indexAction }

#blog:
#    path:      /blog/{page}
#    defaults:  { _controller: AppBundle:Blog:index, page: 1 }
#    requirements:
#        page:  \d+

#contact_form:
#    path:     /contact
#    defaults: { _controller: AppBundle:Main:contactForm }
#    methods:  [GET, POST]

edit_category:
    path:     /admin/product/category/edit
    defaults: { _controller: ProductManagerBundle:ProductCategory:edit }
