oni_add_product:
    path:     /admin/products/add
    defaults: { _controller: oni_product_controller:addAction }

oni_product_list:
    path:     /admin/products
    defaults: { _controller: oni_product_controller:indexAction  }

oni_edit_product:
    path:     /admin/products/edit/{product}
    defaults: { _controller: oni_product_controller:Index:edit }

oni_add_category:
    path:     /admin/product/category/add
    defaults: { _controller: oni_product_categories_controller:addAction }

oni_categories_list:
    path:     /admin/product/categories
    defaults: { _controller: oni_product_categories_controller:indexAction }

oni_ajax_product_list:
    path:     /admin/ajax/product/categories
    defaults: { _controller: oni_product_categories_controller:productListAction  }

#blog:
#    path:      /blog/{page}
#    defaults:  { _controller: AppBundle:Blog:index, page: 1 }
#    requirements:
#        page:  \d+

#contact_form:
#    path:     /contact
#    defaults: { _controller: AppBundle:Main:contactForm }
#    methods:  [GET, POST]

oni_edit_category:
    path:     /admin/product/category/edit/{productCategoryId}
    defaults: { _controller: oni_product_categories_controller:editAction }


oni_delete_category:
    path:     /admin/product/category/delete/{productCategoryId}
    defaults: { _controller: oni_product_categories_controller:deleteAction }