parameters:
    #entities
    product_entity: Cms\ProductManagerBundle\Entity\Products
    product_categories_entity: Cms\ProductManagerBundle\Entity\ProductCategories
    product_category_definitions_entity: Cms\ProductManagerBundle\Entity\ProductCategoryDefinitions
    #repositories
    product_entity_repository: Cms\ProductManagerBundle\Entity\Repository\ProductsRepository
    product_categories_repository: Cms\ProductManagerBundle\Entity\Repository\ProductCategoriesRepository
    product_category_definitions_repository: Cms\ProductManagerBundle\Entity\Repository\ProductCategoryDefinitionsRepository
    #factories
    product_repository_factory: Cms\ProductManagerBundle\Entity\Factory\ProductRespositoryFactory
    #controllers
    product_categories_controller: Cms\ProductManagerBundle\Controller\ProductCategoriesController
    product_controller: Cms\ProductManagerBundle\Controller\IndexController
    #forms
    product_categories_form: Cms\ProductManagerBundle\Form\ProductCategoriesType
    product_category_definitions_form: Cms\ProductManagerBundle\Form\ProductCategoryDefinitionsType
    #events and listeners
    product_event_subscriber: Cms\ProductManagerBundle\EventListeners\ProductEventSubscriber
    product_event: Cms\ProductManagerBundle\Event\ProductEvent

    

services:
    #Entities
    products:
        class:     "%product_entity%"
    product_categories:
        class:     "%product_categories_entity%"
    product_category_definitions:
        class:     "%product_category_definitions_entity%"
    #Repositories
    products_repository:
        class: "%product_entity_repository%"
        factory: [ '@doctrine.orm.default_entity_manager',  getRepository]
        arguments:
                - "%product_entity%"
    product_categories_repository:
        class: "%product_categories_repository%"
        factory: [ '@doctrine.orm.default_entity_manager',  getRepository]
        arguments:
                - "%product_categories_entity%"
    product_categories_service:
        class: Cms\CoreBundle\Repository\CoreRepository
        factory: [ '@repository_factory',  getRepository]
        arguments:
            - '@product_categories_repository'
    product_categories_definitions_repository:
        class: "%product_category_definitions_repository%"
        factory: [ '@doctrine.orm.default_entity_manager',  getRepository]
        arguments:
                - "%product_category_definitions_entity%"
    product_categories_definitions_service:
        class: Cms\CoreBundle\Repository\CoreRepository
        factory: [ '@repository_factory',  getRepository]
        arguments:
            - '@product_categories_definitions_repository'
    #Services
    #Controllers
    product_controller:
        class:     "%product_controller%"
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
                - "@products_repository"
    product_categories_controller:
        class:     "%product_categories_controller%"
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
                - "@product_categories_service"
                - "@product_categories_definitions_service"
    #Forms
    product_categories_form:
        class: "%product_categories_form%"
        arguments:
                - "@service_container"
                - "@session"
        tags:
              - { name: form.type, alias: product_category }
    product_category_definitions_form:
        class: "%product_category_definitions_form%"
        arguments:
                - "@service_container"
        tags:
            - { name: form.type, alias: product_category_definitions }
    #Events and Listeners
    product_event_subscriber:
        class: "%product_event_subscriber%"
        tags:
            - { name: kernel.event_subscriber }
    product_event:
        class: "%product_event%"

    ## CATEGORIES





