parameters:
    #entities
    oni_product_entity: Oni\ProductManagerBundle\Entity\Product
    oni_product_category_entity: Oni\ProductManagerBundle\Entity\ProductCategory
    #repositories
    oni_product_repository: Oni\ProductManagerBundle\Entity\Repository\ProductsRepository
    oni_product_category_repository: Oni\ProductManagerBundle\Entity\Repository\ProductCategoryRepository
    #factories
    oni_product_repository_factory: Oni\ProductManagerBundle\Entity\Factory\ProductRespositoryFactory
    #controllers
    oni_product_category_controller_class: Oni\ProductManagerBundle\Controller\ProductCategoryController
    oni_product_controller_class: Oni\ProductManagerBundle\Controller\ProductController
    #forms
    oni_product_category_form: Oni\ProductManagerBundle\Form\ProductCategoryType
    #events and listeners
    oni_product_event_subscriber: Oni\ProductManagerBundle\EventListeners\ProductEventSubscriber
    oni_product_event: Oni\ProductManagerBundle\Event\ProductEvent

    

services:
    oni_product_controller:
        class: Oni\ProductManagerBundle\Controller\ProductController
        factory: [ "@oni_product_controller_factory", getService ]
        arguments:
              - '@service_container'
    oni_product_option_controller:
        class: Oni\ProductManagerBundle\Controller\ProductOptionController
        factory: [ "@oni_product_option_controller_factory", getService ]
        arguments:
              - '@service_container'
    oni_product_categories_controller:
        class: Oni\ProductManagerBundle\Controller\ProductCategoryController
        factory: [ '@oni_product_categories_controller_factory',  getService ]
        arguments:
            - '@service_container'
    oni_product_service:
        class: Oni\ProductManagerBundle\Service\ProductService
        factory: [ '@oni_product_service_factory', getService ]
        arguments:
            - '@service_container'
    oni_product_type_service:
        class: Oni\ProductManagerBundle\Service\ProductTypeService
        factory: [ '@oni_product_type_service_factory', getService ]
        arguments:
            - '@service_container'
    oni_product_category_service:
        class: Oni\ProductManagerBundle\Service\ProductCategoryService
        factory: [ '@oni_product_category_service_factory', getService ]
        arguments:
            - '@service_container'
    oni_product_option_service:
        class: Oni\ProductManagerBundle\Service\ProductOptionService
        factory: [ '@oni_product_option_service_factory', getService ]
        arguments:
            - '@service_container'
    #Forms
    oni_product_category_form:
        class: Oni\ProductManagerBundle\Form\ProductCategoryForm
        factory: [ '@oni_product_category_form_factory', getService ]
        arguments:
                - "@service_container"
        tags:
              - { name: form.type, alias: oni_product_category_form }
    oni_product_form:
        class: Oni\ProductManagerBundle\Form\ProductForm
        factory: [ '@oni_product_form_factory', getService ]
        arguments:
                - "@service_container"
        tags:
                - { name: form.type, alias: oni_product_form }
    oni_product_option_form:
        class: Oni\ProductManagerBundle\Form\ProductOptionGroupForm
        arguments:
                - "@oni_product_option_service"
        tags:
              - { name: form.type, alias: oni_product_option_form }
    #Events and Listeners
    oni_product_event:
        class: "%oni_product_event%"
    oni_product_event_subscriber:
        class: "%oni_product_event_subscriber%"
        tags:
            - { name: kernel.event_subscriber }





