parameters:
    #entities
    oni_product_entity: Oni\ProductManagerBundle\Entity\Product
    oni_product_category_entity: Oni\ProductManagerBundle\Entity\ProductCategory
    #repositories
    oni_product_repository: Oni\ProductManagerBundle\Entity\Repository\ProductsRepository
    oni_product_category_repository: Oni\ProductManagerBundle\Entity\Repository\ProductCategoryRepository
    #factories
    oni_product_repository_factory: Oni\ProductManagerBundle\Entity\Factory\ProductRespositoryFactory
    #controllers
    oni_product_category_controller_class: Oni\ProductManagerBundle\Controller\ProductCategoryController
    oni_product_controller_class: Oni\ProductManagerBundle\Controller\ProductController
    #forms
    oni_product_category_form: Oni\ProductManagerBundle\Form\ProductCategoryType
    #events and listeners
    oni_product_event_subscriber: Oni\ProductManagerBundle\EventListeners\ProductEventSubscriber
    oni_product_event: Oni\ProductManagerBundle\Event\ProductEvent

    

services:
    #Entities
    oni_product_entity:
        class:     "%oni_product_entity%"
    oni_product_category_entity:
        class:     "%oni_product_category_entity%"
    #Repositories
    oni_products_repository:
        class: "%oni_product_repository%"
        factory: [ '@oni_repository_factory',  getRepository]
        arguments:
                - "%oni_product_entity%"
    oni_product_categories_repository:
        class: "%oni_product_category_repository%"
        factory: [ '@oni_repository_factory',  getRepository]
        arguments:
            - '%oni_product_category_entity%'
    #Services

    #Controllers
    oni_product_controller_class:
        class: "%oni_product_controller_class%"
    oni_product_category_controller_class:
        class: "%oni_product_category_controller_class%"
    oni_product_controller:
        class: "%oni_product_controller_class%"
        factory: [ '@oni_controller_factory',  getController]
        arguments:
            - '@oni_product_controller_class'
    oni_product_categories_controller:
        class: "%oni_product_category_controller_class%"
        factory: [ '@oni_controller_factory',  getController]
        arguments:
            - '@oni_product_category_controller_class'
#    oni_product_categories_controller:
#        class: "%oni_product_categories_controller%"
#        calls:
#            - [setContainer, ["@service_container"]]
#            - [setTranslator, ["@translator"]]
        arguments:
            - "@oni_product_categories_repository"
    #Forms
    oni_product_category_form:
        class: "%oni_product_category_form%"
        arguments:
                - "@service_container"
        tags:
              - { name: form.type, alias: oni_product_category }
    #Events and Listeners
    oni_product_event:
        class: "%oni_product_event%"
    oni_product_event_subscriber:
        class: "%oni_product_event_subscriber%"
        tags:
            - { name: kernel.event_subscriber }


    ## CATEGORIES





