<?php

namespace App\Oni\ProductManagerBundle\Entity;

/**
 * CurrenciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
