<?php

namespace Cms\ProductManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductVariantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVariantsRepository extends EntityRepository
{
}
