<?php

namespace Cms\ProductManagerBundle\Repository;
use Gedmo\Translatable\Entity\Repository\TranslationRepository;

/**
 * ProductCategoryTranslationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryTranslationsRepository extends TranslationRepository
{
}
