<?php

namespace Cms\ProductManagerBundle\Repository;

/**
 * ProductCategoryTranslationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryTranslationsRepository extends \Doctrine\ORM\EntityRepository
{
}
