<?php

namespace App\Oni\ProductManagerBundle\Repository;

/**
 * ProductFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
