<?php

namespace Cms\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Cms\CoreBundle\Repository\CoreRepository;
/**
 * ProductCategoryDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryDefinitionsRepository extends CoreRepository
{

    public function getFormProductCategoryChoices(){

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select(array(
                'pcd'
            ))
            ->from($this->productCategoryDefinitionsTable, 'pcd')
            ->where('pcd.languageId = :lang')
            ->setParameter('lang', $this->languageId);

        $results = $qb->getQuery()->getResult();

        return $results;

    }

}
