<?php

namespace Oni\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * productOptionGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionGroupRepository extends EntityRepository
{
}
