<?php

namespace Cms\ProductManagerBundle\Entity\Repository;

use Cms\CoreBundle\CoreGlobals;
use Cms\CoreBundle\Entity\Languages;
use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\NestedTreeRootRepositoryTest;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
/**
 * ProductCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoriesRepository extends NestedTreeRepository
{
    /**
     * Set via Repository Factory
     */
    public $languageId;


    public function getAllProductCategories(){

        $return = array(
            'results' => array(),
            'titles' => array()
        );

        $keys = array(
            'Category Id' => 'pc.id',
            'Category Name' => 'pcd.productCategoryName'
        );


        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select($keys)
            ->from(CoreGlobals::PRODUCT_CATEGORIES_ENTITY, 'pc')
            ->innerjoin(CoreGlobals::PRODUCT_CATEGORIES_DEFINITION_ENTITY, 'pcd', 'WITH' , 'pc.id = pcd.productCategoryId AND pcd.languageId = :lang')
            ->setParameter('lang', $this->languageId);

        $results = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        $return['results'] = $results;
        $return['titles'] = $keys;


        return $return;

    }

    /****
     *
     * Get product all product categories for Form
     *
     * @return mixed
     *
     */
    public function getFormProductCategoryChoices(){

        $categories = $this->findAll();
        $return = array();

        //Because product category names are stored in the product_category_definitions table
        //We need to call the setProductCategoryName() method which will retrieve the name
        //and set the productCategoryName variable with in the entity
       // var_dump($categories); exit;
        foreach ($categories as $category){


            $return[] = $category;

        }

        return $categories;

    }


}
