<?php

namespace Cms\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryDefinitionsRepository extends EntityRepository
{
}
