<?php

namespace Oni\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryDefinitionsRepository extends EntityRepository
{

    public function getFormProductCategoryChoices(){

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select(array(
                'pcd'
            ))
            ->from($this->productCategoryDefinitionsTable, 'pcd')
            ->where('pcd.languageId = :lang')
            ->setParameter('lang', $this->getLanguageId());

        $results = $qb->getQuery()->getResult();

        return $results;

    }

}
