<?php

namespace Cms\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{

    public $languageId;

    public function getAllProduct(){


    }

}
