<?php

namespace Cms\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductOptionDefinitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionDefinitionsRepository extends EntityRepository
{
}
