<?php

namespace App\Oni\ProductManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use App\Oni\CoreBundle\Doctrine\Spec\Specification;
use App\Oni\CoreBundle\Entity\Repository\RepositorySpecificationInterface;

/**
 * productOptionGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionGroupRepository extends EntityRepository implements RepositorySpecificationInterface
{

    /**
     * @param Specification $specification
     * @return array
     */
    public function match(Specification $specification)
    {
        if ( ! $specification->supports($this->getEntityName())) {
            throw new \InvalidArgumentException("Specification not supported by this repository.");
        }

        $qb = $this->createQueryBuilder('pog');
        $expr = $specification->match($qb, 'pog');
        $query = $qb->where($expr)->getQuery();
        $specification->modifyQuery($query);

        return $query->getResult();
    }
}
