Oni\ProductManagerBundle\Entity\ProductCategory:
    properties:
        name:
            - NotBlank: ~
#            - Regex:
#                pattern: '/^[\\\/:\*\?"<>\|]+$/'
#                message: name.can.only.contain
            - Length:
                min: 3
                max: 30
                minMessage: two.or.more.chars
                maxMessage: fifty.or.less.chars.
        url:
            - NotBlank: ~
            - Regex:
                pattern: '/^[\w\d_-]+$/'
                message: url.can.only.contain
            - Length:
                min: 2
                max: 50
                minMessage: two.or.more.chars
                maxMessage: fifty.or.less.chars
        description:
            - NotBlank: ~
            - Type:
                type: string
        metaTitle:
            - NotBlank: ~
            - Type:
                type: string
            - Length:
                min: 2
                minMessage: two.or.more.chars
                max: 50
                maxMessage: fifty.or.less.chars
        metaDescription:
            - Type:
                type: string
            - Length:
                max: 100
                maxMessage: onehundred.or.less.chars
        metaKeyWords:
            - Type:
                type: string
            - Length:
                max: 50
                maxMessage: fifty.or.less.chars
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [url]
            errorPath: url
            message: url.already.in.use
