Cms\ProductManagerBundle\Entity\ProductCategory:
    properties:
        productCategoryName:
            - NotBlank: ~
            - Type:
                type: alpha
                message: Product Category Name {{ value }} is not a valid {{ type }}.
            - Length:
                min: 3
                minMessage: Name is too short. It should have 3 characters or more.

